Models/DangKiHoc.cs
using lab1.models;
using Microsoft.Extensions.ObjectPool;

namespace lab1.models;

public class DangKiHoc
{

    // Var
    public int Id { get; set; }
    public int LearnerID { get; set; }
    public int CourseID { get; set; }
    public virtual Course Course { get; set; }
    public virtual Learner Learner { get; set; }
}

Areas/Admin/Controllers/CourseController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
//
using lab1.models;
using lab1.models.viewmodels;
using lab1.services;
using lab1.data;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace lab1.areas.admin.controllers;

[Area("Admin")]
public class CourseController : Controller
{
    // Var
    private SchoolContext _schoolContext;

    // Constructor
    public CourseController(SchoolContext context)
    {
        _schoolContext = context;
    }

    // Actions

    /**
     * Medthod: Get
     * Description: Get list of Course
     */
    public IActionResult Index() {
        var listCourse = _schoolContext.Courses.ToList();
        return View(listCourse);
    }

    /**
     * Medthod: Get
     * Description: Create new Course
     */
    public IActionResult Create() {
        return View();
    }

    /**
     * Medthod: Post
     * Description: Create new Course
     */
    [HttpPost]
    public IActionResult Create(Course course) {
        if (!ModelState.IsValid) {
            return View();
        }
        _schoolContext.Courses.Add(course);
        _schoolContext.SaveChanges();

        return RedirectToAction("Index");
    }

    /**
     * Method: Get
     * Description: Get details of Course
     */
    public IActionResult Details(int Id) {
        var course = _schoolContext.Courses.FirstOrDefault(c => c.CourseID == Id);

        return View(course);
    }

    /**
     * Method: Post
     * Description: Edit Course Details with id
     */
    [HttpPost]
    public IActionResult Details(Course course) {
        if (!ModelState.IsValid) {
            return View("Details", course);
        }
        
        var _course = _schoolContext.Courses.FirstOrDefault(c => c.CourseID == course.CourseID);

        _course.Title = course.Title;
        _course.Credits = course.Credits;

        _schoolContext.SaveChanges();

        return RedirectToAction("Index");
    }
    
    /**
     * Method: Post
     * Description: Delete a course
     */
    [HttpPost]
    public ActionResult Delete(int Id) {
        var course = _schoolContext.Courses.FirstOrDefault(
            c => c.CourseID == Id);
        _schoolContext.Courses.Remove(course);
        _schoolContext.SaveChanges();
        return RedirectToAction("Index");
    }
}

Areas/Admin/Controllers/DangKiHocController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
//
using lab1.models;
using lab1.models.viewmodels;
using lab1.services;
using lab1.data;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace lab1.areas.admin.controllers;

[Area("Admin")]
public class DangKiHocController : Controller
{
    // Var
    private SchoolContext _schoolContext;

    // Constructor
    public DangKiHocController(SchoolContext context)
    {
        _schoolContext = context;
    }

    // Actions

    /**
     *  GET: Admin/DangKiHoc
     *  Get list data of DangKiHoc
     */
    public IActionResult Index()
    {
        var dangkiHocs = _schoolContext.DangKiHocs
            .Include(e => e.Course)
            .Include(e => e.Learner)
            .ToList();

        return View(dangkiHocs);
    }

    /**
     *  GET: Admin/DangKiHoc/Create
     *  Create new DangKiHoc
     */
    public IActionResult Create()
    {
        ViewBag.ListLearner = new List<SelectListItem>();
        foreach (var learner in _schoolContext.Learners.ToList())
        {
            if (!IsCourseAll(learner.LearnerID))
            {
                ViewBag.ListLearner.Add(
                    new SelectListItem
                    {
                        Value = learner.LearnerID.ToString(),
                        Text = learner.FirstMidName.ToString() + " " + learner.LastName.ToString()
                    }
                );
            }
        }

        return View();
    }

    /**
     *  POST: Admin/DangKiHoc/Create
     *  Create new DangKiHoc
     */
    [HttpPost]
    public IActionResult Create(CreateDangKiHoc model)
    {
        if (ModelState.IsValid)
        {
            foreach (int idCourse in model.CourseID)
            {
                var dangkiHoc = new DangKiHoc
                {
                    LearnerID = model.LearnerID,
                    CourseID = idCourse
                };

                _schoolContext.DangKiHocs.Add(dangkiHoc);
            }
            _schoolContext.SaveChanges();
            return RedirectToAction("Index");
        }

        // string listCourseId = "";
        // foreach (int idCourse in model.CourseID) {
        //     listCourseId += idCourse + ", ";
        // }
        // System.Console.WriteLine(
        //     $"LearnerID: {model.LearnerID}, listIdCourse: {listCourseId}"
        // );

        ViewBag.ListLearner = new List<SelectListItem>();
        foreach (var learner in _schoolContext.Learners.ToList())
        {
            if (!IsCourseAll(learner.LearnerID))
            {
                ViewBag.ListLearner.Add(
                    new SelectListItem
                    {
                        Value = learner.LearnerID.ToString(),
                        Text = learner.FirstMidName.ToString() + " " + learner.LastName.ToString()
                    }
                );
            }
        }
        return View(model);
    }

    /**
     * DELETE: Admin/DangKiHoc/Delete/{id}
     * Delete DangKiHoc by id
     */
    public IActionResult Delete(int id)
    {
        var dangkiHoc = _schoolContext.DangKiHocs.Find(id);
        if (dangkiHoc == null)
        {
            return NotFound();
        }

        _schoolContext.DangKiHocs.Remove(dangkiHoc);
        _schoolContext.SaveChanges();

        return RedirectToAction("Index");
    }

    // API

    /**
     * GET: Admin/DangKiHoc/GetUnregisteredCourse/{id}
     * Get list course Unregistered by Learner
     */
    [HttpGet]
    public IActionResult GetUnregisteredCourse(int id)
    {
        var listCourse = _schoolContext.Courses.ToList();
        var listDangKiHoc = _schoolContext.DangKiHocs.Where(e => e.LearnerID == id).ToList();
        var res = new List<Course>();

        foreach (var course in listCourse)
        {
            if (listDangKiHoc.Find(e => e.CourseID == course.CourseID) == null)
            {
                res.Add(course);
            }
        }

        return Json(res);
    }

    // Helpper Kiem tra sinh vien co da dang ki tat ca cac hoc phan khong
    private bool IsCourseAll(int LearnerID)
    {

        int SumCourse = _schoolContext.Courses.Count();
        var CourseOfLearner = _schoolContext.DangKiHocs
                .Where(e => e.LearnerID == LearnerID);
        if (SumCourse == CourseOfLearner.Count()) return true;
        return false;
    }
}

Areas/Admin/Controllers/LearnerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
//
using lab1.data;
using lab1.models;
using System.Runtime.InteropServices;
using Microsoft.VisualBasic;

namespace lab1.areas.admin.controllers;

[Area("Admin")]
public class LearnerController : Controller
{
    // Variables
    private SchoolContext db;
    private int pageSize = 3;

    // Constructor
    public LearnerController(SchoolContext context)
    {
        db = context;
    }

    // GET: Learner
    public IActionResult Index(int? id)
    {
        var learners = db.Learners
            .Include(m => m.Major);

        if (id != null)
        {
            learners = db.Learners
                .Where(l => l.MajorID == id)
                .Include(m => m.Major);
        }

        int pageNum = (int)Math.Ceiling(learners.Count() / (float)pageSize);
        ViewBag.pageNum = pageNum;
        ViewBag.pageIndexCurrent = 1;

        var result = learners.Take(pageSize).ToList();

        return View(result);
    }

    // GET: Create a new Learner
    public IActionResult Create()
    {
        ViewBag.MajorID = GetViewBagMajorID();
        return View();
    }

    // POST: Create a new Learner
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(
        [Bind("FirstMidName, LastName ,MajorID, EnrollmentDate")]
            Learner learner
    )
    {
        if (ModelState.IsValid)
        {
            db.Learners.Add(learner);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        // Else return to the form 
        ViewBag.MajorID = GetViewBagMajorID();
        return View();
    }

    // GET: Edit a Learner
    public IActionResult Edit(int id)
    {
        if (id == null || db.Learners == null)
            return NotFound();

        var learner = db.Learners.Find(id);

        if (learner == null)
            return NotFound();

        ViewBag.MajorID = GetViewBagMajorID();
        return View(learner);
    }

    // POST: Edit a Learner
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(int id,
        [Bind("LearnerID, FirstMidName, LastName, MajorID, EnrollmentDate")]
            Learner learner
    )
    {
        if (id != learner.LearnerID)
            return NotFound();

        if (ModelState.IsValid)
        {
            try
            {
                db.Update(learner);
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!LearnerExists(learner.LearnerID))
                {
                    return NotFound();
                }
                else
                    throw;
            }
            return RedirectToAction(nameof(Index));
        }
        ViewBag.MajorId = GetViewBagMajorID();
        return View(learner);
    }

    // GET: Delete a Learner
    public IActionResult Delete(int id)
    {
        if (id == null || db.Learners == null)
            return NotFound();

        var learner = db.Learners.Include(l => l.Major)
                .Include(e => e.Enrollments)
                .FirstOrDefault(m => m.LearnerID == id);

        if (learner == null)
        {
            return NotFound();
        }

        if (learner.Enrollments.Count() > 0)
        {
            return Content("This learner has some enrollments, can't delete!");
        }

        return View(learner);
    }

    // POST: Delete a Learner
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public IActionResult DeleteConfirmed(int id)
    {
        if (db.Learners == null)
        {
            return Problem("Entity set 'Learners' is null");
        }
        var learner = db.Learners.Find(id);
        if (learner != null)
        {
            db.Learners.Remove(learner);
        }
        db.SaveChanges();
        return RedirectToAction(nameof(Index));
    }

    // GET: Learner by MajorID - Help ajax
    public ActionResult LearnerByMajorID(int id)
    {
        var learners = db.Learners
           .Include(m => m.Major)
           .Where(m => m.MajorID == id)
           .ToList();

        return PartialView("LearnerTable", learners);
    }

    // GET: 
    public ActionResult LearnerFilter(int? id, string? keyword, int? pageIndex)
    {
        IQueryable<Learner> learners = db.Learners;
        int page = (int)(pageIndex == null || pageIndex <= 0 ? 1 : pageIndex);

        if (id != null)
        {
            learners = learners.Where(l => l.MajorID == id);
            ViewBag.MajorID = id;
        }

        if (!string.IsNullOrEmpty(keyword))
        {
            learners = learners.Where(l => l.FirstMidName.ToLower().Contains(keyword.ToLower()));
            ViewBag.keyword = keyword;
        }

        int pageNum = (int)Math.Ceiling(learners.Count() / (float)pageSize);
        ViewBag.pageNum = pageNum;
        ViewBag.pageIndexCurrent = page;

        var result = learners.Skip(pageSize * (page - 1))
            .Take(pageSize)
            .Include(m => m.Major)
            .ToList();

        return PartialView("LearnerTable", result);
    }

    /**
     * GET: Dang ki mon hoc
     */
    public IActionResult DangKiMonHoc(int id)
    {
        // Get Learner
        var Learner = db.Learners.Find(id);
        ViewBag.Learner = Learner;

        // Get the courses the learner has chosen
        var courseChoices = db.DangKiHocs
            .Where(l => l.LearnerID == id)
            .Include(c => c.Course)
            .ToList();

        // Store in ViewBag for use in the View
        ViewBag.CourseChoices = courseChoices;

        // Get all courses
        var courses = db.Courses.AsQueryable();

        // Get the courses the learner has NOT chosen
        var chosenCourseIds = courseChoices.Select(cc => cc.Course.CourseID).ToList();

        ViewBag.CourseDontChoice = courses
            .Where(c => !chosenCourseIds.Contains(c.CourseID))
            .ToList();

        return View();

    }

    /**
     * POST: Dang ki mon hoc
     */
    [HttpPost]
    public IActionResult DangKiMonHoc(List<int> CourseId, int learnerID)
    {
        foreach (var courseID in CourseId)
        {
            DangKiHoc dangKiHoc = new DangKiHoc
            {
                LearnerID = learnerID,
                CourseID = courseID
            };
            db.DangKiHocs.Add(dangKiHoc);
        }

        db.SaveChanges();

        return RedirectToAction(nameof(DangKiMonHoc));
    }

    /**
     * POST: Huy Dang Ki Mon Hoc
     */
    [HttpPost]
    public IActionResult HuyDangKiMonHoc(List<int> CourseId, int learnerID)
    {
        foreach (var courseID in CourseId)
        {
            DangKiHoc dangKiHoc = db.DangKiHocs.FirstOrDefault(d =>
                        d.LearnerID == learnerID && d.CourseID == courseID);
            if (dangKiHoc != null)
            {
                db.DangKiHocs.Remove(dangKiHoc);
            }
        }

        db.SaveChanges();

        return RedirectToAction(nameof(DangKiMonHoc), new { id = learnerID });
    }

    /**
     * List Help funtion
     */

    // Help funtion Get ViewBag MajorID 
    private List<SelectListItem> GetViewBagMajorID()
    {
        var majors = new List<SelectListItem>();

        foreach (var item in db.Majors)
        {
            majors.Add(
                new SelectListItem
                {
                    Text = item.MajorName,
                    Value = item.MajorID.ToString()
                }
            );
        }

        return majors;
    }

    // Help function to check if Learner exists
    private bool LearnerExists(int id)
    {
        return (db.Learners?.Any(e => e.LearnerID == id)).GetValueOrDefault();
    }
}

Areas/Admin/Views/DangKiHoc/Create.cshtml
@using lab1.models.viewmodels
@model CreateDangKiHoc

@{
    ViewData["Title"] = "Dang Ki Hoc";
}

<div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-area="Admin" asp-controller="DangKiHoc" asp-action="Create" method="post" class="mt-3">
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="@Model.LearnerID" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <select asp-for="@Model.LearnerID" asp-items="ViewBag.ListLearner" class="form-control"></select>
            </div>
            <span asp-validation-for="@Model.LearnerID" class="text-danger"></span>
        </div>
        <div id="listCheckBoxCourse" style="margin: 7px" class="form-group row">

        </div>
        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </div>
    </form>
</div>

@section Scripts {
<script>

    const GetUnregisteredCourse = (learnerId) => {
        return new Promise((resolve, reject) => {
            $.ajax({
                url: '/Admin/DangKiHoc/GetUnregisteredCourse',
                type: 'GET',
                data: { id: learnerId },
                success: function (response) {
                    resolve(response);
                },
                accepts: 'application/json',
                error: function (error) {
                    reject(error);
                }
            });
        });
    };

    const CreateCheckBoxCourse = (courses) => {
        let listRadioCourse = $('#listCheckBoxCourse');
        listRadioCourse.empty();
        courses.forEach(course => {
            let radio = `<div class="form-check">
                                <input class="form-check ajax-checkbox" 
                                    type="checkbox" 
                                    name="CourseID" 
                                    id="course-${course.courseID}" 
                                    value="${course.courseID}">
                                <label class="form-check ajax-checkbox-label" for="course-${course.courseID}">
                                    ${course.title}
                                </label>
                            </div>`;
            listRadioCourse.append(radio);
        });
    };

    $(document).ready(function () {
        // Get default
        GetUnregisteredCourse($('#LearnerID').val()).then(courses => {
            CreateCheckBoxCourse(courses);
        }).catch(error => {
            console.error("Failed to load courses", error);
        });

        $('#LearnerID').change(function () {
            var learnerId = $(this).val();
            console.log('LearnerID changed to ID' + learnerId);
            GetUnregisteredCourse(learnerId).then(courses => {
                CreateCheckBoxCourse(courses);
            }).catch(error => {
                console.error("Failed to load courses", error);
            });
        });
    });
</script>
}

Areas/Admin/Views/DangKiHoc/Index.cshtml
@using lab1.models
@model IEnumerable<DangKiHoc>
@{
    ViewData["Title"] = "Dang ki hoc";
}

<a asp-action="Create" asp-area="Admin" asp-controller="DangKiHoc" class="btn btn-primary">Dang Ki Hoc</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Learner Name</th>
            <th>Course Title</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model)
        {
            <tr>
                <td>
                    @s.Id
                <td>
                    <a asp-action="Edit" 
                        asp-area="Admin" 
                        asp-controller="Learner" 
                        asp-route-id="@s.LearnerID">
                            @(s.Learner.FirstMidName + " " + s.Learner.LastName)
                    </a>
                </td>
                <th>
                    <a asp-action="Details" 
                        asp-area="Admin" 
                        asp-controller="Course" 
                        asp-route-id="@s.CourseID">
                            @s.Course.Title
                    </a>
                </th>
                @{
                    <td>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-danger" data-toggle="modal" 
                            data-target="#deleteModal-@s.Id">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-trash" viewBox="0 0 16 16">
                                <path
                                    d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z" />
                                <path
                                    d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z" />
                            </svg>
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="deleteModal-@s.Id" tabindex="-1" role="dialog"
                            aria-labelledby="deleteModalLabel-@s.Id" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteModalLabel-@s.Id">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                                class="bi bi-exclamation-triangle" viewBox="0 0 16 16">
                                                <path
                                                    d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.15.15 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.2.2 0 0 1-.054.06.1.1 0 0 1-.066.017H1.146a.1.1 0 0 1-.066-.017.2.2 0 0 1-.054-.06.18.18 0 0 1 .002-.183L7.884 2.073a.15.15 0 0 1 .054-.057m1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767z" />
                                                <path
                                                    d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0M7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0z" />
                                            </svg>
                                        </h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Bạn Muốn Xoá ID: @s.Id ?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Không</button>
                                        <form asp-action="Delete" asp-area="Admin" asp-controller="DangKiHoc" asp-route-Id="@s.Id" method="post">
                                            <input type="hidden" name="id" value="@s.Id" />
                                            <button type="submit" class="btn btn-danger">Đồng Ý</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                }
            </tr>
        }
        </tbody>
    </table>

            @section Scripts {
    <script>

    </script>
}