Areas/Admin/Controllers/NavLeftItemController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
//
using lab1.models;
using lab1.models.viewmodels;
using lab1.services;
using lab1.data;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace lab1.areas.admin.controllers;

[Area("Admin")]
public class NavLeftItemController : Controller
{
    // Var
    private readonly lab1.data.ViewContext _context;

    // Constructor
    public NavLeftItemController(lab1.data.ViewContext context)
    {
        _context = context;
    }

    // Actions

    /**
     * Medthod: Get
     * Description: Get list of NavLeftDashboardAdmin
     */
    public IActionResult Index() {
        var listCourse = _context.NavLeftDashboardAdmin.ToList();
        return View(listCourse);
    }

    /**
     * Medthod: Get
     * Description: Create new NavLeftDashboardAdmin
     */
    public IActionResult Create() {
        return View();
    }

    /**
     * Medthod: Post
     * Description: Create new NavLeftDashboardAdmin
     */
    [HttpPost]
    public IActionResult Create(NavItem navItem) {
        if (!ModelState.IsValid) {
            return View();
        }
        // navItem.ID = _context.NavLeftDashboardAdmin.Max(c => c.ID) + 1;  
        _context.NavLeftDashboardAdmin.Add(navItem);
        _context.SaveChanges();

        return RedirectToAction("Index");
    }

    /**
     * Method: Get
     * Description: Get details of NavLeftDashboardAdmin
     */
    public IActionResult Details(int Id) {
        var course = _context.NavLeftDashboardAdmin.FirstOrDefault(
            c => c.ID == Id
        );

        return View(course);
    }

    /**
     * Method: Post
     * Description: Edit NavLeftDashboardAdmin Details with id
     */
    [HttpPost]
    public IActionResult Details(NavItem navItem) {
        if (!ModelState.IsValid) {
            return View("Detail", navItem.ID);
        }
        
        var _nav = _context.NavLeftDashboardAdmin.FirstOrDefault(
            c => c.ID == navItem.ID
        );

        _nav.Area = navItem.Area;
        _nav.Controller = navItem.Controller;
        _nav.Action = navItem.Action;
        _nav.Text = navItem.Text;

        _context.SaveChanges();

        return RedirectToAction("Index");
    }
    
    /**
     * Method: Post
     * Description: Delete a NavLeftDashboardAdmin
     */
    [HttpPost]
    public ActionResult Delete(int Id) {
        var nav = _context.NavLeftDashboardAdmin.FirstOrDefault(
            c => c.ID == Id
        );
        _context.NavLeftDashboardAdmin.Remove(nav);
        _context.SaveChanges();
        
        return RedirectToAction("Index");
    }
}

Areas/Admin/Views/NavLeftItem/Create.cshtml
@using lab1.models
@model NavItem

@{
    ViewData["Title"] = "Create Student";
}

<div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-area="Admin" asp-controller="NavLeftItem" asp-action="Create" method="post" class="mt-3">
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Area" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Area" class="form-control" placeholder="Area">
            </div>
            <span asp-validation-for="Area" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Controller" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Controller" class="form-control" placeholder="Controller">
            </div>
            <span asp-validation-for="Controller" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Action" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Action" class="form-control" placeholder="Action">
            </div>
            <span asp-validation-for="Action" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Text" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Text" class="form-control" placeholder="Text">
            </div>
            <span asp-validation-for="Text" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/Admin/Views/NavLeftItem/Details.cshtml
@using lab1.models
@model NavItem

@{
    ViewBag.Title = "Detail";
}

<div class="container-xl px-4 mt-4">
    <hr class="mt-0 mb-4">
    <div class="row">
            <div class="card mb-4">
                <div class="card-body">
                    <form asp-action="Details"  asp-area="Admin" asp-controller="NavLeftItem">                        
                        <div class="mb-3">
                            <label class="small mb-1" asp-for="Area">Area</label>
                            <input asp-for="Area" class="form-control" 
                                placeholder="Enter your Area" value="@Model.Area">
                            <span asp-validation-for="Area" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label class="small mb-1" asp-for="Controller">Controller</label>
                            <input asp-for="Controller" class="form-control" 
                                placeholder="Enter your Controller" value="@Model.Controller">
                            <span asp-validation-for="Controller" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label class="small mb-1" asp-for="Action">Action</label>
                            <input asp-for="Action" class="form-control" 
                                placeholder="Enter your Action" value="@Model.Action">
                            <span asp-validation-for="Action" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label class="small mb-1" asp-for="Text">Text</label>
                            <input asp-for="Text" class="form-control" 
                                placeholder="Enter your Text" value="@Model.Text">
                            <span asp-validation-for="Text" class="text-danger"></span>
                        </div>
                        <!-- Save changes button-->
                        <input hidden class="hidden" asp-for="ID" value="@Model.ID">
                        <button class="btn btn-primary" type="submit">Save changes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/NavLeftItem/Index.cshtml
@using lab1.models
@model IEnumerable<NavItem>
@{
    ViewData["Title"] = "List Nav Left Item";
}

<a asp-action="Create" asp-area="Admin" asp-controller="NavLeftItem" class="btn btn-primary">Create nav item</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Mã</th>
            <th>Area</th>
            <th>Controller</th>
            <th>Action</th>
            <th>Text</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model)
        {
                <tr>
                    <td>
                        <a asp-action="Details" asp-area="Admin" asp-controller="NavLeftItem" asp-route-id="@s.ID">@s.ID</a>
                    </td>
                    <td>@s.Area</td>
                    <td>@s.Controller</td>
                    <td>@s.Action</td>
                    <td>@s.Text</td>
                    <td>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal-@s.ID">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-trash" viewBox="0 0 16 16">
                                <path
                                    d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z" />
                                <path
                                    d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z" />
                            </svg>
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="deleteModal-@s.ID" tabindex="-1" role="dialog"
                            aria-labelledby="deleteModalLabel-@s.ID" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteModalLabel-@s.ID">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                                class="bi bi-exclamation-triangle" viewBox="0 0 16 16">
                                                <path
                                                    d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.15.15 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.2.2 0 0 1-.054.06.1.1 0 0 1-.066.017H1.146a.1.1 0 0 1-.066-.017.2.2 0 0 1-.054-.06.18.18 0 0 1 .002-.183L7.884 2.073a.15.15 0 0 1 .054-.057m1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767z" />
                                                <path
                                                    d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0M7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0z" />
                                            </svg>
                                        </h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Bạn Muốn Xoá Nav Item: @s.ID ?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Không</button>
                                        <form asp-action="Delete" asp-area="Admin" asp-controller="NavLeftItem" method="post">
                                            <input type="hidden" name="id" value="@s.ID" />
                                            <button type="submit" class="btn btn-danger">Đồng Ý</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
        }
    </tbody>
</table>

@section Scripts {
        <script>

        </script>
}